name: Node Continuous Integration

on:
  pull_request:
    branches:
      - master
      - sprint_*

jobs:
  client_ci:
    runs-on: ubuntu-latest
    env:
      REACT_APP_SERVER_URL: "http://localhost:9000"
      REACT_APP_CLIENT_URL: "http://localhost:3000"
      DB_CONN: "mongodb://localhost:27017/data"
      DB_USER: "admin"
      DB_PW: "password"
    steps:
      - name: Git checkout
        uses: actions/checkout@v2

      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - run: npm ci --prefix server
      - run: npm ci --prefix client
      - name: npx cypress run --spec cypresss/integration/FrontEndTests/*
        uses: cypress-io/github-action@v2
        with:
          record: true
          start: npm start
          wait-on: "http://localhost:3000"
          working-directory: client
        env:
          CYPRESS_RECORD_KEY: 2b71c803-ef27-425a-b947-72b0d0dfdf25
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.3.0
        with:
          mongodb-version: 4.4
      - name: Add admin user    
        run: echo 'db.createUser({user:"admin", pwd:"password", roles:[]});' | mongo data
      - name: npx cypress run --spec cypresss/integration/End2EndTests/*
        uses: cypress-io/github-action@v2
        with:
          record: true
          start: npm start, npm run startserver
          wait-on: "http://localhost:3000, http://localhost:9000"
          working-directory: client
        env:
          CYPRESS_RECORD_KEY: 2b71c803-ef27-425a-b947-72b0d0dfdf25
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: npm run build --if-present --prefix client
  server_ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - run: npm ci --prefix server
      - run: npm test --if-present --prefix server
      - run: npm run build --if-present --prefix server
