name: Node Continuous Integration

on:
  pull_request:
    branches: [master]

jobs:
  client_ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - run: npm ci --prefix client
      - run: npm run test-ci --if-present --prefix client
      - run: npm run build --prefix client
  server_ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - run: npm ci --prefix server
      - run: npm test --if-present --prefix server
      - run: npm run build --prefix server
