name: Node Continuous Integration

on:
  pull_request:
    branches:
      - master
      - sprint_*

jobs:
  client_ci:
    runs-on: ubuntu-latest
    env:
      REACT_APP_SERVER_URL: "http://localhost:9000"
      REACT_APP_CLIENT_URL: "http://localhost:3000"
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - run: npm ci --prefix client
      - name: cypress run
        uses: cypress-io/github-action@v2
        with:
          record: true
          start: npm start
          wait-on: "http://localhost:3000"
          working-directory: client
        env:
          CYPRESS_RECORD_KEY: 2b71c803-ef27-425a-b947-72b0d0dfdf25
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: npm run build --if-present --prefix client
  server_ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - run: npm ci --prefix server
      - run: npm test --if-present --prefix server
      - run: npm run build --if-present --prefix server
